### ISSUE TITLE
Feedback on Sept 2016 release

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/visualization-novice#12]
Please add comments to this issue to give feedback on the Sept 2016 release of the draft of this lesson.  We also welcome new issues, or PRs with suggested changes.

**Comment by naupaka** [comment]
Great topic and I think many people would find it useful, especially the parts about how to decide what to do (perhaps even more so than how to do it).

My other initial thought is that this is a really ambitious timeline to cover all of this content for people who have not seen it before. `dplyr` and `ggplot2` both bring a pretty different syntax that will be new to many, even if they are experienced in base R.  Is the idea that this is a half-day chunk for part of a SWC workshop? a full day? A standalone lesson?

**Comment by karawoo** [comment]
I'm excited to see a lesson on data visualization, and I have some thoughts on the current structure. The lessons focus a lot on specific plot types, both in the "Choosing a Good Chart" graphic and in the lessons "Generating a Line Histogram" (this term confused me; I think 'density plot' is more common), "Bubble Charts", and "Stacked Area Chart". I'm curious about the decision to structure the lessons this way given that ggplot2 is explicitly designed _not_ to create visualizations based on plot type, but rather to provide a consistent grammar for mapping data to visual elements. This grammar is really advantageous once you've got new data that doesn't lend itself to a bubble chart or stacked area chart, and it doesn't seem like these lessons really reinforce it. I think the visualization section of [R for Data Science](http://r4ds.had.co.nz/data-visualisation.html) does a good job with this.

I'd also love to see some discussion of graphical perception and which types of visual encodings are most effective for nominal/ordinal/quantitative data. The key point from the "Choosing a Good Chart" lesson is "A good chart directly and clearly addresses a scientific question" -- understanding and choosing appropriate visual encodings is crucial for this, and the Choosing a Good Chart image doesn't really cover it.

That said, I agree with @naupaka that the timeline is ambitious, particularly the dplyr and tidy data sections. I'd budget at least three times as much time for dplyr, or you could cut it and give learners data in the format they'll need, assuming that data wrangling will get covered elsewhere in the workshop. I would also consider cutting tidy data -- it's important but doesn't connect much with the rest of the lesson and would take much, much more than 10 minutes.

**Comment by ashiklom** [comment]
Big :+1: on "density plot" rather than "line histogram", especially since the relevant R and `ggplot` functions have `density` right in the name.

More generally, I think a really cool approach given such a meaningful data set would be to introduce a real overarching science question and hypothesis at the beginning and show how to break that question down into smaller questions that can each be answered by a plot. For example, you could start with a hypothesis like: "Improvements in quality of life affect populations of developed / wealthy and developing / poor countries differently, resulting in rapid population growth in the former and weak population decline in the latter" and then take the learners through the process of breaking that down into smaller questions that can each be answered with a plot. This has the advantage that it would have value even to students that end up doing their visualizations and analyses in Matlab, Python, or anything else.

**Comment by brymz** [comment]
Thanks for the quick and thoughtful responses, @naupaka, @karawoo, & @ashiklom!

I think a couple points of clarification can help focus the feedback... 

> This is a really ambitious timeline.

For our timeline, I assume that participants are not seeing `dplyr`, `tidyr` and `ggplot2` for the first time but have some practical experience, taken the SWC or DC novice lessons, or expanded the workshop to include a half day of introduction. In that way, the material presented is a review with a focus on the decision-making process and implementation of publication quality figures.

> The lessons focus a lot on specific plot types.

Greg and I were inspired to develop this lesson by the "Choosing a good chart" graphic and structured the lesson around the decision-making framework depicted therein. The specific plot types and terms are direct results of keying out a data visualization or research question on the graphic.

Although the `ggplot2` grammar transcends specific plot types, it does allow the user to generate a specific plot by mapping the data to a desired visual element. I agree that it is an important goal to convey the generality of the `ggplot2` process. I have attempted this by threading the general mapping of `ggplot2` as the lesson passes by each of the specific plots. With this goal in mind, I wrote the continuous set of faded challenge problems in the episodes after the break to grow in complexity and build on one another. They require participants to identify and fill in common parts that were introduced in previous challenge problems.

> some discussion of graphical perception and which types of visual encodings are most effective for nominal/ordinal/quantitative data

This concept will first be introduced in the 'Data Structures' episode as continuous and categorical variables and will be revisited for each specific plot during the decision-making step. I could see how we could expand from the "Choosing a good chart" language to include more of this from a deeper statistical framework.

> introduce a real overarching science question and hypothesis at the beginning and show how to break that question down into smaller questions that can each be answered by a plot.

Great idea! Going in the plot type to research question direction to develop the lesson, I'm not sure that I did a great job leading to a broader overarching question. But, I agree that this would be a great way to more generally appeal to the scientific process and the big goals of the lesson.

**Comment by aflaxman** [comment]
This has been really helpful for me, because I am designing an introduction to visualization lecture right now, as well.  I will only have a hour, so I'll be able to do much less than you have here, but it has been great for me to see your process and what you have included.

One tough choice for me is should I include any software at all?  I don't expect all of the attendees (post-docs and fellows, with a physician-scientist background) to know R, but they probably all have used excel.  Maybe instead of creating charts with software, I'll focus on sketching charts with pencil and paper. I see that you have included a lot of the data wrangling steps necessary to really create charts in R here, so I wonder if you have thoughts on my situation?

The thing that I want to include which I do not see in your plan is some techniques and practice on "visualization critique".  My goal is to give the audience the language and tools for improving their abilities in an on-going manner long after the lecture is done.  I have used a format for this previously that I adapted from a UW-Madison design lab website which I cannot find now, encouraging students to focus on aspects of a design starting from Conceptual (What are its goals and does it accomplish them?), then on Aesthetic (Overall appeal, objects, iconography, contrast, value, size, positioning, hierarchy, consistency, ...), and only then on Technical details.  

I was happy with this, but I wonder if it provides enough guidance.  I found a slide deck from Jeff Heer's interactive data visualization class that provides more detail and structure for critique: http://courses.cs.washington.edu/courses/cse512/15sp/lectures/CSE512-Critique.pdf (page 15-16)

There are some other things I would like to include, but I don't think I have time.  Maybe you do, or maybe together we can think of a way to integrate them or allude to them without taking much time for time: theory of visual perception; tradeoffs between novel and familiar visual forms; exploratory vs explanatory data visualization.

Thanks for your work on this!

**Comment by brymz** [comment]
Thanks for reaching out to us, @aflaxman! 

We definitely have plans to include some sort of "visualization critique" as part of our decision-making process. Our challenge exercises include 'good' and 'bad' examples of the different charts that we cover. I would be excited to help you work out a brief version of our lesson that does not rely on coding (I can easily make the output figures available to you) and get some more detailed ideas about your "visualization critique" strategy.

I likely won't get back to this for a couple of weeks. What is the timeline for wrapping up your lecture?

**Comment by brymz** [comment]
@aflaxman: For reference the figures for the lesson are stored in https://github.com/swcarpentry/visualization-novice/tree/gh-pages/fig and should find their way to a page where they are grouped on the website. This `figures` page might be a good place to structure your lecture-style visualization critique.

**Comment by aflaxman** [comment]
I've got to get my title, learning objectives, and advertising material in order today, but I have until Oct 21 to put together the lesson.  Thanks for sharing the figures!  

My hosts have already mentioned their concern about respecting copyrights---do you have concerns about using the "Chart Suggestions" figure in your lesson?

**Comment by brymz** [comment]
> about respecting copyrights---do you have concerns about using the "Chart Suggestions" figure in your lesson?

That's a good and very important question. The Software Carpentry instructional materials are CC-BY (see [licence](https://swcarpentry.github.io/visualization-novice/license/)), but I am not sure about the 'The Extreme Presentation' materials. There is clearly a copyright on the image, but I wasn't able to find a license on [their website](http://extremepresentation.typepad.com/blog/). Any thoughts, @gvwilson?

**Comment by aflaxman** [comment]
I've given my talk, here is the material: https://github.com/aflaxman/iths-communicating-results-visually  I ended up not including the Chart Suggestions figure in the presentation itself, but directing everyone to it as the very next thing to do if they want to learn more.  I think things went well.

Also two days after I spoke, I came across this additional, reusable material from OHSU: https://github.com/OHSUBD2K/BDK18-Data-Visualization

**Comment by brymz** [comment]
Thanks for the materials, @aflaxman. I hope you had a good response to your talk.
